#!/bin/bash

# run a command once at a particualar time.


IFS="
"

LOG=$HOME/at/at.log
REQ=$HOME/at/at.req

# SAMPLE at.req
#20220807-0105 $HOME/bin/getYoutube
#20220809-0100 $HOME/bin/getOdooVids


NOW=$(date "+%Y%m%d-%H%M")

logheader() {
    echo "----------------------------" >> $LOG
    echo "$NOW" >> $LOG
}

COUNT=0

for L in $(cat $REQ)
do
    #echo $L
    WHEN=$(echo $L | cut -c1-13)
    if [ $WHEN == $NOW ]
    then
        [ $COUNT -lt 1 ] && logheader
        ((COUNT++))
        COMMAND=$(echo $L | cut -c15-)
        echo "WHEN=$WHEN, COMMAND=$COMMAND" >> $LOG
        bash -c "$COMMAND &"
    fi
done
